name: Publish Node Package
author: mrcointreau
description: Publish npm packages using a standalone action for manual runs or recovery. For new releases, prefer release workflow with publish=true for atomic release+publish (no tag/release if publish fails)

inputs:
  node-version:
    description: Node.js version
    required: false
    default: "22"
  working-directory:
    description: Working directory
    required: false
    default: "."
  npm-token:
    description: NPM token for publishing, optional if using OIDC trusted publishing
    required: false
  use-oidc:
    description: Use OIDC trusted publishing (recommended), set to 'false' to use npm-token instead
    required: false
    default: "true"
  install-command:
    description: Install command to run
    required: false
    default: "npm ci"
  build-command:
    description: Build command to run
    required: false
    default: "npm run build"
  version:
    description: Version being published (for determining npm tag)
    required: true
  dist-directory:
    description: Directory containing the built package to publish
    required: false
    default: "dist"

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.install-command }}

    - name: Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.build-command }}

    - name: Publish to npm
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
        NPM_CONFIG_PROVENANCE: ${{ inputs.use-oidc == 'true' && inputs.npm-token == '' && 'true' || '' }}
      run: |
        # Validate: require npm-token when not using OIDC
        if [ "${{ inputs.use-oidc }}" != "true" ] && [ -z "${{ inputs.npm-token }}" ]; then
          echo "::error::npm-token is required when use-oidc is false"
          exit 1
        fi

        # Determine tag from version (e.g., 1.0.0-beta.1 -> beta)
        VERSION="${{ inputs.version }}"
        if [[ "$VERSION" == *"-"* ]]; then
          PUBLISH_TAG="${VERSION#*-}"
          PUBLISH_TAG="${PUBLISH_TAG%%.*}"
        else
          PUBLISH_TAG="latest"
        fi

        cd "${{ inputs.dist-directory }}"
        PUBLISH_ARGS=""
        if [ "${{ inputs.use-oidc }}" = "true" ]; then
          PUBLISH_ARGS="--provenance"
        fi

        npm publish --tag "$PUBLISH_TAG" $PUBLISH_ARGS
