name: Publish Python Package
author: mrcointreau
description: Publish PyPI packages using a standalone action for manual runs or recovery. For new releases, prefer release workflow with publish=true for atomic release+publish (no tag/release if publish fails)

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.12"
  working-directory:
    description: Working directory
    required: false
    default: "."
  pypi-token:
    description: PyPI token for publishing, optional if using OIDC trusted publishing
    required: false
  use-oidc:
    description: Use OIDC trusted publishing (recommended), set to 'false' to use pypi-token instead
    required: false
    default: "true"
  build-command:
    description: Build command to run
    required: false
    default: "uv build"

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
      with:
        enable-cache: true

    - name: Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.build-command }}

    - name: Publish to PyPI
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        PYPI_TOKEN: ${{ inputs.pypi-token }}
        USE_OIDC: ${{ inputs.use-oidc }}
      run: |
        if [ "$USE_OIDC" = "true" ]; then
          uv publish --trusted-publishing always
        elif [ -n "$PYPI_TOKEN" ]; then
          UV_PUBLISH_TOKEN="$PYPI_TOKEN" uv publish
        else
          echo "::error::pypi-token is required when use-oidc is false"
          exit 1
        fi
